[global]
refresh = 500
display = "Tui"

[[servers]]
name = "MAC"
host = "10.210.126.58"
user = "harkerhand"
privkey_path = "C:\\Users\\harkerhand\\.ssh\\id_ed25519"
monitors = ["Mem", "Disk", "Cpu", "Net"]

[[servers]]
name = "ALI"
host = "47.97.243.238"
user = "root"
privkey_path = "C:\\Users\\harkerhand\\.ssh\\id_ed25519"
monitors = ["Mem", "Disk", "Cpu", "Net"]
